// The ordered install pipeline. Each step is { title, run } where run(onData)
// resolves to { ok, detail }. The runner halts on the first failure so the TUI
// can show exactly which step broke and the captured stderr.

import { writeFileSync, mkdirSync } from 'node:fs';
import { sh, bash, log } from './sh.js';
import { APPS } from './catalog.js';

const MNT = '/mnt';
const NIXOS_DIR = `${MNT}/etc/nixos`;

const PL = {
  boot: '/dev/disk/by-partlabel/BOOT',
  swap: '/dev/disk/by-partlabel/swap',
  root: '/dev/disk/by-partlabel/nixos',
};

export function hostNixContents(cfg) {
  const browser = cfg.apps.includes('chromium') ? 'chromium' : 'firefox';
  return `# Generated by the nixos-rice installer.
# Edit and run: sudo nixos-rebuild switch --flake /etc/nixos
{
  username  = "${cfg.username}";
  hostname  = "${cfg.hostname}";
  gpu       = "${cfg.gpu}";
  timezone  = "${cfg.timezone}";
  locale    = "${cfg.locale}";
  browser   = "${browser}";
}
`;
}

// Build apps.nix from the selected app ids (see ../lib/catalog.js).
export function appsNixContents(cfg) {
  const pkgs = [];
  const raw = [];
  const modules = [];
  const imports = [];

  for (const id of cfg.apps) {
    const a = APPS[id];
    if (!a) continue;
    if (a.pkgs) pkgs.push(...a.pkgs);
    if (a.raw) raw.push(...a.raw);
    if (a.modules) modules.push(...a.modules);
    if (a.imports) imports.push(...a.imports);
  }

  // ollama: GPU acceleration follows the chosen GPU vendor.
  if (cfg.apps.includes('ollama')) {
    const accel = cfg.gpu.startsWith('nvidia') ? '"cuda"' : cfg.gpu === 'amd' ? '"rocm"' : 'false';
    modules.push(`services.ollama = {\n    enable = true;\n    acceleration = ${accel};\n  };`);
  }

  // yazi as default file manager: install it + udiskie automount + udisks2.
  if (cfg.fileManager === 'yazi') {
    pkgs.push('yazi', 'udiskie');
    modules.push('services.udisks2.enable = true;');
  }

  const pkgList = [...pkgs, ...raw];
  const importsBlock = imports.length
    ? `  imports = [\n${imports.map((i) => '    ' + i).join('\n')}\n  ];\n\n`
    : '';
  const pkgsBlock = pkgList.length
    ? `  environment.systemPackages = with pkgs; [\n${pkgList.map((p) => '    ' + p).join('\n')}\n  ];\n\n`
    : '';
  const modulesBlock = modules.length ? modules.map((m) => '  ' + m).join('\n\n') + '\n' : '';

  return `# Generated by the nixos-rice installer — optional applications.
{ config, pkgs, lib, inputs, ... }:

{
${importsBlock}${pkgsBlock}${modulesBlock}}
`;
}

export function buildSteps(cfg) {
  const steps = [];

  // 1. Partition the disk (GPT: ESP + optional swap + root). Destructive.
  steps.push({
    title: `Partitioning ${cfg.disk}`,
    run: (onData) =>
      bash(
        `
        DISK="${cfg.disk}"
        SWAP="${cfg.swapGiB}"
        # Clean up any previous run.
        umount -R ${MNT} 2>/dev/null || true
        swapoff -a 2>/dev/null || true
        wipefs -a "$DISK"
        sgdisk --zap-all "$DISK"
        sgdisk -n1:0:+512M -t1:ef00 -c1:BOOT "$DISK"
        if [ "$SWAP" -gt 0 ]; then
          sgdisk -n2:0:+\${SWAP}G -t2:8200 -c2:swap "$DISK"
          sgdisk -n3:0:0       -t3:8300 -c3:nixos "$DISK"
        else
          sgdisk -n2:0:0       -t2:8300 -c2:nixos "$DISK"
        fi
        partprobe "$DISK"
        udevadm settle
        `,
        { onData }
      ).then((r) => ({ ok: r.code === 0, detail: r.stderr })),
  });

  // 2. Format and mount.
  steps.push({
    title: 'Formatting and mounting filesystems',
    run: (onData) =>
      bash(
        `
        mkfs.fat -F32 -n BOOT ${PL.boot}
        mkfs.ext4 -F -L nixos ${PL.root}
        ${cfg.swapGiB > 0 ? `mkswap -L swap ${PL.swap}\nswapon ${PL.swap}` : ''}
        udevadm settle
        mount ${PL.root} ${MNT}
        mkdir -p ${MNT}/boot
        mount -o umask=0077 ${PL.boot} ${MNT}/boot
        `,
        { onData }
      ).then((r) => ({ ok: r.code === 0, detail: r.stderr })),
  });

  // 3. Clone the configuration repo into /mnt/etc/nixos.
  steps.push({
    title: 'Cloning nixos-rice configuration',
    run: (onData) =>
      bash(
        `
        mkdir -p ${MNT}/etc
        rm -rf ${NIXOS_DIR}
        git clone --depth 1 "${cfg.repoUrl}" ${NIXOS_DIR}
        `,
        { onData }
      ).then((r) => ({ ok: r.code === 0, detail: r.stderr })),
  });

  // 4. Generate the hardware config for THIS machine (overwrites the placeholder).
  //    --show-hardware-config prints to stdout so we don't clobber configuration.nix.
  steps.push({
    title: 'Detecting hardware (nixos-generate-config)',
    run: async (onData) => {
      const r = await sh('nixos-generate-config', ['--root', MNT, '--show-hardware-config'], {
        onData,
      });
      if (r.code !== 0) return { ok: false, detail: r.stderr };
      try {
        writeFileSync(`${NIXOS_DIR}/hardware-configuration.nix`, r.stdout);
        log('wrote hardware-configuration.nix');
        return { ok: true, detail: '' };
      } catch (e) {
        return { ok: false, detail: String(e) };
      }
    },
  });

  // 5. Write host.nix with the user's choices.
  steps.push({
    title: 'Writing host.nix (username, hostname, GPU, locale)',
    run: async () => {
      try {
        writeFileSync(`${NIXOS_DIR}/host.nix`, hostNixContents(cfg));
        return { ok: true, detail: '' };
      } catch (e) {
        return { ok: false, detail: String(e) };
      }
    },
  });

  // 5b. Write apps.nix from the optional-app checklist.
  steps.push({
    title: 'Writing apps.nix (optional applications)',
    run: async () => {
      try {
        writeFileSync(`${NIXOS_DIR}/apps.nix`, appsNixContents(cfg));
        return { ok: true, detail: '' };
      } catch (e) {
        return { ok: false, detail: String(e) };
      }
    },
  });

  // 5c. Patch the rice for chosen default terminal / file manager.
  const needsPatch = cfg.apps.includes('ghostty') || cfg.fileManager === 'yazi';
  if (needsPatch) {
    steps.push({
      title: 'Setting default terminal / file manager in the rice',
      run: (onData) => {
        const cfgDir = `${NIXOS_DIR}/config/sessions/hyprland/config`;
        const ghostty = cfg.apps.includes('ghostty')
          ? `sed -i 's/kitty/ghostty/g' "${cfgDir}/variables.conf"`
          : 'true';
        const yazi = cfg.fileManager === 'yazi'
          ? `sed -i 's|exec, nautilus|exec, $terminal -e yazi|' "${cfgDir}/keybindings.conf"
             echo 'exec-once = udiskie &' >> "${cfgDir}/autostart.conf"`
          : 'true';
        return bash(`${ghostty}\n${yazi}`, { onData }).then((r) => ({
          ok: r.code === 0,
          detail: r.stderr,
        }));
      },
    });
  }

  // 6. Fetch ilyamiro's wallpapers into the new user's home.
  steps.push({
    title: "Fetching ilyamiro's wallpapers",
    run: (onData) =>
      bash(
        `
        # NOTE: capital "Wallpapers" — this is the path the rice's wallpaper
        # picker (qs_manager.sh) defaults to ($HOME/Pictures/Wallpapers).
        WALLDIR="${MNT}/home/${cfg.username}/Pictures/Wallpapers"
        mkdir -p "$(dirname "$WALLDIR")"
        rm -rf "$WALLDIR"
        git clone --depth 1 "${cfg.wallpapersUrl}" "$WALLDIR"
        rm -rf "$WALLDIR/.git"
        # Default first-user uid is 1000, primary group "users" is gid 100.
        chown -R 1000:100 "${MNT}/home/${cfg.username}"
        `,
        { onData }
      ).then((r) => ({ ok: r.code === 0, detail: r.stderr })),
  });

  // 7. The actual install + build. This is the long one.
  steps.push({
    title: 'Installing NixOS (nixos-install — this takes a while)',
    run: (onData) =>
      sh(
        'nixos-install',
        [
          '--flake',
          `${NIXOS_DIR}#${cfg.hostname}`,
          '--no-root-passwd',
          '--option',
          'experimental-features',
          'nix-command flakes',
        ],
        { onData }
      ).then((r) => ({ ok: r.code === 0, detail: r.stderr })),
  });

  // 8. Set the user's password inside the freshly installed system.
  steps.push({
    title: `Setting password for ${cfg.username}`,
    run: () =>
      sh('nixos-enter', ['--root', MNT, '-c', 'chpasswd'], {
        input: `${cfg.username}:${cfg.password}\n`,
        secret: true,
      }).then((r) => ({ ok: r.code === 0, detail: r.stderr })),
  });

  // 9. Set the root password (nixos-install ran with --no-root-passwd).
  steps.push({
    title: 'Setting root password',
    run: () =>
      sh('nixos-enter', ['--root', MNT, '-c', 'chpasswd'], {
        input: `root:${cfg.rootPassword}\n`,
        secret: true,
      }).then((r) => ({ ok: r.code === 0, detail: r.stderr })),
  });

  return steps;
}
